---
# example for a list
# - description: "checks docker containers status-code"
#   path: /usr/local/monscripts/docker-status-code.sh
#   name: docker-status-code
#
- name: "create destination directories"
  file:
    path: "{{ fpath }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0500"
  
  loop:
    - "{{ custom_metrics_root }}"
    - "{{ custom_metrics_root }}/status"
    - "{{ textfile_metrics_location }}"
    - "{{ monscripts_location }}"
    - "{{ systemd_services_location }}"
    - "{{ systemd_timers_location }}"

  loop_control:
    loop_var: "fpath"

- name: "copy monitoring scripts to remote"
  template:
    src: "files/scripts/{{ monscript }}"
    dest: "{{ monscripts_location }}"
    owner: "root"
    group: "root"
    mode: "0500"
  
  loop:
    - "check-fstab.sh"
    - "list-processes.sh"
  
  loop_control:
    loop_var: "monscript"

- name: "utilize systemd"
  include_tasks: "systemd.yaml"
  loop: "{{ monitoring_scripts }}"
  loop_control:
    loop_var: "monscript"
