---
- name:
  debug:
    var: monscript

- name: "create a systemd-service for the monitoring script"
  ansible.builtin.template:
    src: "systemd-service.j2"
    dest: "{{ systemd_timers_location }}/{{ systemd_prefix }}.{{ monscript.name }}.service"
    owner: "root"
    group: "root"
    mode: "0400"

- name: "create a systemd-timer for the monitoring script service"
  ansible.builtin.template:
    src: "systemd-timer.j2"
    dest: "{{ systemd_timers_location }}/{{ systemd_prefix }}.{{ monscript.name }}.timer"
    owner: "root"
    group: "root"
    mode: "0400"

- name: "create the systemd-service on-failure handler"
  ansible.builtin.template:
    src: "systemd-on-failure.j2"
    dest: "{{ systemd_timers_location }}/{{ systemd_prefix }}.{{ monscript.name }}.failure.service"
    owner: "root"
    group: "root"
    mode: "0400"

- name: "enable --now the systemd-timer for the monitoring script timer"
  ansible.builtin.systemd_service:
    name: "{{ systemd_prefix }}.{{ monscript.name }}.timer"
    state: "started"
    enabled: "true"
